version: 0.0
os: linux
files:
  - source: /app_files/
    destination: /var/www/html/test_app_deploy
permissions:
  - object: /
    pattern: "**"
    owner: pi
    group: pi
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 60
      runas: app
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: app
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: app
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: app
